name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *" # Runs every 24 hours (at minute 0, every 24th hour)
  workflow_dispatch: # Allow manual trigger

permissions: # <--- ADD THIS BLOCK HERE
  contents: write # <--- This grants write permission to push changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: NingenUman # Your username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is correct

      - name: Commit snake SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg
          git commit -m "Generate GitHub snake" || echo "No changes to commit"
          git push
